version: '3.8'
services:
  db:
    container_name: db
    image: postgres:13.2
    restart: always
    ports:
      - ${DB_PORT}:5432
    environment:
      - POSTGRESS_USER=${DB_USER}
      - POSTGRESS_PASSWORD=${DB_PASS}
      - POSTGRESS_DB=${DB_NAME}
